version: '3.7'

services:
  azo-db:
    image: mysql:8.0.29
    container_name: azo-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=azo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    restart: always